### ISSUE TITLE
Lack of example in README

### ISSUE THREAD

**Issue by ZiperRom1** [usnistgov/hedgehog#1]
The code seems well written but it lacks of some simple / complex examples in README to show how to use your tasks pipeline stuff.

**Comment by tblattner** [comment]
Thanks for the comments! 

We have tutorials in the works, which we will be deploying by the end of this month once review of the documentation is completed. I'll see if we expedite some of the basic tutorials as those are actually finalized at this point.

**Comment by tblattner** [comment]
Hello,

Wanted to update you that we have pushed some examples/tutorials: https://github.com/usnistgov/hedgehog-Tutorials

There will be a matching web-page sometime later this month or into next as we await for approval for the public facing web content.
